// <auto-generated />
using System;
using LinkedInJobMatcher.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkedInJobMatcher.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LinkedInJobMatcher.Data.Post", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.HasIndex("Status");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("LinkedInJobMatcher.Data.PostEmail", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId", "RecruiterId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("PostEmails");
                });

            modelBuilder.Entity("LinkedInJobMatcher.Data.Recruiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ContactedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Recruiters");
                });

            modelBuilder.Entity("LinkedInJobMatcher.Data.PostEmail", b =>
                {
                    b.HasOne("LinkedInJobMatcher.Data.Post", "Post")
                        .WithMany("PostEmails")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkedInJobMatcher.Data.Recruiter", "Recruiter")
                        .WithMany("PostEmails")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("LinkedInJobMatcher.Data.Post", b =>
                {
                    b.Navigation("PostEmails");
                });

            modelBuilder.Entity("LinkedInJobMatcher.Data.Recruiter", b =>
                {
                    b.Navigation("PostEmails");
                });
#pragma warning restore 612, 618
        }
    }
}
